
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: LaLoyd Theme
description: A description of your site can go here!
nav-links:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Writing
    url: /writing

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      is_post: true
permalink: /:title

# Where things are
source              : .
destination         : ./_site
plugins_dir         : _plugins
layouts_dir         : _layouts
includes_dir        : _includes
sass:
  sass_dir: _sass
  style: compressed




